### ISSUE TITLE
deploy-a-highly-available-jenkins-cluster-on-aws

### ISSUE THREAD

**Issue by devopsdymyr** [mlabouardy/aws-pipeline#1]
@mlabouardy Environment is deployed succesfully with my subdomain jenkins.vgshub.com after that i have tried to login with user name mlabouardy and password getting error.
please check below screenshots 
![screenshot from 2019-02-28 12-40-29](https://user-images.githubusercontent.com/41105507/53547894-3a215500-3b56-11e9-9389-304d6b7e9008.png)
![screenshot from 2019-02-28 12-39-22](https://user-images.githubusercontent.com/41105507/53547896-3a215500-3b56-11e9-831b-59787d6df498.png)

**Comment by devopsdymyr** [comment]
terraform.tfvars file details in this file
![screenshot from 2019-02-28 12-51-11](https://user-images.githubusercontent.com/41105507/53548507-9cc72080-3b57-11e9-9cb1-dabadbf95ec2.png)

**Comment by mlabouardy** [comment]
did you set the username & password while creating the Jenkins AMI with Packer (https://github.com/mlabouardy/aws-pipeline/blob/master/deploy-a-highly-available-jenkins-cluster-on-aws/packer/jenkins-master/basic-security.groovy)

**Comment by devopsdymyr** [comment]
@mlabouardy Wow it's working

**Comment by mlabouardy** [comment]
Awesome
