### ISSUE TITLE
Unable to build the jenkins master image with Linux ami-id : ami-0274e11dced17bb5b

### ISSUE THREAD

**Issue by geeks18** [mlabouardy/aws-pipeline#2]
amazon-ebs: Complete!
    amazon-ebs: Setup SSH key
    amazon-ebs: Configure Jenkins
    amazon-ebs: /tmp/install-plugins.sh: line 2: $'\r': command not found
    amazon-ebs: : invalid option
    amazon-ebs: set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
    amazon-ebs: /tmp/install-plugins.sh: line 4: $'\r': command not found
    amazon-ebs: /tmp/install-plugins.sh: line 7: $'\r': command not found
    amazon-ebs: /tmp/install-plugins.sh: line 9: $'\r': command not found
    amazon-ebs: /tmp/install-plugins.sh: line 10: syntax error near unexpected token `$'{\r''
    amazon-ebs: '
    amazon-ebs: Job for jenkins.service failed because the control process exited with error code. See "systemctl status jenkins.service" and "journalctl -xe" for details.
    amazon-ebs: Starting jenkins (via systemctl):  [FAILED]
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: No volumes to clean up, skipping
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Script exited with non-zero exit status: 1

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Script exited with non-zero exit status: 1

==> Builds finished but no artifacts were created.

**Comment by mlabouardyfox** [comment]
$'\r' error is due unix format -> https://stackoverflow.com/questions/11616835/r-command-not-found-bashrc-bash-profile
