### ISSUE TITLE
deploy-a-highly-available-jenkins-cluster-on-aws

### ISSUE THREAD

**Issue by devopsdymyr** [mlabouardy/aws-pipeline#4]
Step 1: without update this ssh private key created image and launched first time and i have realized jenkins worker node is in offline due to ssh access.
Step 2: Now update jenkins username password and docker,github but little confusion on ssh -private key update on jenkins master image with packer under file "node-agent.groovy"
![screenshot from 2019-03-08 21-51-31](https://user-images.githubusercontent.com/41105507/54040878-61c68c00-41ec-11e9-8e00-58d3932a6abc.png)
step 3: under session Build an AWS VPC Using Infrastructure as Code created one key in the name demo so i can use that private key (/home/devops/.ssh/id_rsa) on all location of Node-agen.groovy file right
![screenshot from 2019-03-08 22-01-12](https://user-images.githubusercontent.com/41105507/54041445-c0403a00-41ed-11e9-876d-9a71f9d86c7e.png)

**Comment by devopsdymyr** [comment]
Output jenkins error
![screenshot from 2019-03-08 23-05-15](https://user-images.githubusercontent.com/41105507/54045118-bb33b880-41f6-11e9-81fb-0b88827f0d60.png)
![screenshot from 2019-03-08 23-04-39](https://user-images.githubusercontent.com/41105507/54045119-bbcc4f00-41f6-11e9-9fb4-95aa1d73e9f6.png)

**Comment by mlabouardy** [comment]
did you copy the ssh private key to your jenkins-master packer folder ?

**Comment by devopsdymyr** [comment]
No just copy paste inside node-agent.groovy,i will try to copy inside that jenkins master directory

**Comment by devopsdymyr** [comment]
Still have same issue after copying id_rsa file to master-jenkins directory .while building master-AMI ssh-key picked from ~/.ssh/id_rsa  
![Screenshot from 2019-03-12 05-45-08](https://user-images.githubusercontent.com/41105507/54166415-2ac1d600-448b-11e9-9792-61e122b86352.png)
![Screenshot from 2019-03-12 05-57-11](https://user-images.githubusercontent.com/41105507/54166542-b89dc100-448b-11e9-8064-51499a19e918.png)

**Comment by mlabouardy** [comment]
you need to set the terraform variable `jenkins_credentials_id` to `jenkins-slaves`

**Comment by devopsdymyr** [comment]
![Screenshot from 2019-03-14 16-31-42](https://user-images.githubusercontent.com/41105507/54351944-b186d680-4676-11e9-971f-c0f4702ec270.png)
Thanks it's working

**Comment by ahmed20391849** [comment]
i have a problem with jenkins!
no slave was detected !!!
![2019-06-20](https://user-images.githubusercontent.com/34915846/59870975-cae69f80-9396-11e9-9bc0-03dc15fd496a.png)
can any one help me please!
